### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by kylegibbons** [bartbutenaers/node-red-contrib-wav-headers#1]
Hi,

When I run `npm install node-red-contrib-wav-headers` I get "Not Found"

**Comment by bartbutenaers** [comment]
Hey Kyle (@kylegibbons),,

Indeed I had developed this contribution to experiment with web audio streaming in Node-RED.  But I have never published it to NPM...

If I remember correctly **adding** WAV headers worked fine in my case, but **removing** WAV headers was not correctly implemented.  Will try to fix that issue this weekend and delivery you a beta version on NPM.  Would be nice if you could test that and give me feedback, before I make it available for a larger audience...

Will keep you updated !
Bart

**Comment by bartbutenaers** [comment]
Hey Kyle (@kylegibbons ),

I have published a beta version on NPM, which you can install like this:
```
npm install node-red-contrib-wav@1.0.0-beta.1
```
Could you test this please and give me feedback?
If it works correctly, I will publish a final version on NPM.
Bart

**Comment by kylegibbons** [comment]
Thanks! Will be trying it now.

**Comment by bartbutenaers** [comment]
Hey Kyle,
I have meanwhile published version 1.0.0 on NPM for another user.  So you can install it also via your Node-red (palette) menu if you like...
Bart
