### ISSUE TITLE
Seems to have stopped working

### ISSUE THREAD

**Issue by mcdonaldajr** [bartbutenaers/node-red-contrib-wav-headers#4]
Tried out test flow, and no output from the node. Debug window shows input OK, but no output.
Tried on Pi running latest versions of everything (node red v1.2.6).
Also tried on a MacBook running node red v1.0.6.

Anthony

**Comment by bartbutenaers** [comment]
Hi,
I have tried the flow, but I don't see anything that is not working...
Both debug nodes show information in the Debug sidebar:

![image](https://user-images.githubusercontent.com/14224149/101281396-ecc42400-37ce-11eb-861a-613c6926f1d3.png)

And I hear the voice speaking in my browser.

With ***"no output"*** do you mean that you don't hear the voice speaking?    Or do the messages not appear in the Debug sidebar?

P.S. Are there any errors in the Node-RED server log?

Bart

**Comment by mcdonaldajr** [comment]
Both. The first debug produces output.
payload: object
chunkID: "RIFF"
chunkSize: 253160
format: "WAVE"
compression: 1
numChannels: 2
sampleRate: 44100
byteRate: 176400
blockAlign: 4
bitsPerSample: 16
_msgid: "cfcc26e0.0e5e18"

The 2nd debug isn't triggered. No sound output either.
node-red-log doesn't show anything.
I have checked that node-red-contrib-play-audio is installed.
I've had this working before on other Pi's. This is a fresh build.

Must be something silly I've done if you have it working.

**Comment by bartbutenaers** [comment]
Hmm, no idea what could be going wrong...
Some separate tests might perhaps give us an idea:

1. With this basic flow you should hear the sound, based on its original WAV headers:
   
   ![image](https://user-images.githubusercontent.com/14224149/101289207-55c19100-37fb-11eb-9cc4-b1d1d343154a.png)
   ```
   [{"id":"517652c0.768f2c","type":"http request","z":"42b7b639.325dd8","name":"Download WAV file","method":"GET","ret":"bin","paytoqs":false,"url":"https://www.pacdv.com/sounds/voices/open-the-goddamn-door.wav","tls":"","proxy":"","authType":"basic","x":490,"y":1620,"wires":[["c817d86b.429548"]]},{"id":"c504e163.5f81c","type":"inject","z":"42b7b639.325dd8","name":"Start test","repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":300,"y":1620,"wires":[["517652c0.768f2c"]]},{"id":"c817d86b.429548","type":"play audio","z":"42b7b639.325dd8","name":"","voice":"0","x":710,"y":1620,"wires":[]}]
   ```
2. With this flow:

   ![image](https://user-images.githubusercontent.com/14224149/101289243-8b667a00-37fb-11eb-8024-99a9d666941b.png)
   ```
   [{"id":"56d1edd3.8e0814","type":"wav-headers","z":"42b7b639.325dd8","name":"","action":"del","channels":"1","samplerate":"22050","bitwidth":"16","x":660,"y":1740,"wires":[["24f32d3a.3dad22"],[]]},{"id":"81183ee6.d94bb","type":"http request","z":"42b7b639.325dd8","name":"Download WAV file","method":"GET","ret":"bin","paytoqs":false,"url":"https://www.pacdv.com/sounds/voices/open-the-goddamn-door.wav","tls":"","proxy":"","authType":"basic","x":430,"y":1740,"wires":[["56d1edd3.8e0814"]]},{"id":"395a1fdd.edf43","type":"inject","z":"42b7b639.325dd8","name":"Start test","repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":240,"y":1740,"wires":[["81183ee6.d94bb"]]},{"id":"24f32d3a.3dad22","type":"debug","z":"42b7b639.325dd8","name":"WAV without headers","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":920,"y":1740,"wires":[]}]
   ```
   You should see the buffer without WAV headers:

   ![image](https://user-images.githubusercontent.com/14224149/101289297-db454100-37fb-11eb-826c-0d59b245ef70.png)

3. And with this flow:

   ![image](https://user-images.githubusercontent.com/14224149/101289307-ee581100-37fb-11eb-8122-181fccf399bb.png)
   ```
   [{"id":"480a6928.cd5398","type":"wav-headers","z":"42b7b639.325dd8","name":"","action":"del","channels":"1","samplerate":"22050","bitwidth":"16","x":580,"y":1820,"wires":[["484a15fd.3c56fc"],[]]},{"id":"b2134388.6f46d","type":"http request","z":"42b7b639.325dd8","name":"Download WAV file","method":"GET","ret":"bin","paytoqs":false,"url":"https://www.pacdv.com/sounds/voices/open-the-goddamn-door.wav","tls":"","proxy":"","authType":"basic","x":350,"y":1820,"wires":[["480a6928.cd5398"]]},{"id":"41b5dfc.fff992","type":"inject","z":"42b7b639.325dd8","name":"Start test","repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":160,"y":1820,"wires":[["b2134388.6f46d"]]},{"id":"484a15fd.3c56fc","type":"wav-headers","z":"42b7b639.325dd8","name":"","action":"add","channels":"2","samplerate":"44100","bitwidth":"16","x":830,"y":1820,"wires":[["3a1fdd5b.a7e792"],[]]},{"id":"3a1fdd5b.a7e792","type":"debug","z":"42b7b639.325dd8","name":"WAV without headers","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1080,"y":1820,"wires":[]}]
   ```
   You should see a buffer that is a bit bigger (since it has headers):
   
   ![image](https://user-images.githubusercontent.com/14224149/101289342-1cd5ec00-37fc-11eb-83f2-3eff1b7093d9.png)

**Comment by mcdonaldajr** [comment]
Interesting, works on Chrome browser, but not on Safari. Obviously no problem with your software.
